"""Export a JSON centroid model as a C header for MCU deployment.

The MCU side does not have a JSON parser by default, and including one would
spend flash that should go to feature extraction and inference instead. The
embedded convention is to bake the trained parameters into a const struct at
compile time, which is what this script produces.

Usage:
    python scripts/export_model_to_c.py \
        --model artifacts/model.json \
        --out firmware/model_params.h \
        --fixed-out firmware/model_params_fixed.h \
        --name g_centroid_model
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import numpy as np

from tpm.fixed_point import Q_FRACTIONAL_BITS, FixedPointCentroid
from tpm.model import CentroidAnomalyDetector


def _format_float_array(values: list[float]) -> str:
    """Render a Python list as a C float array initializer with stable line breaks."""

    chunks: list[str] = []
    for i in range(0, len(values), 4):
        line = ", ".join(f"{v:.9e}f" for v in values[i : i + 4])
        chunks.append("    " + line)
    return ",\n".join(chunks)


def _format_int32_array(values: list[int]) -> str:
    """Render a Python integer list as a C int32_t array initializer."""

    chunks: list[str] = []
    for i in range(0, len(values), 6):
        line = ", ".join(f"{int(v)}" for v in values[i : i + 6])
        chunks.append("    " + line)
    return ",\n".join(chunks)


def render_header(payload: dict, struct_name: str) -> str:
    """Build the C header text from a parsed JSON model payload."""

    feature_names = payload["feature_names"]
    mean = payload["mean"]
    scale = payload["scale"]
    threshold = float(payload["threshold"])
    n = len(feature_names)
    if len(mean) != n or len(scale) != n:
        raise ValueError(
            "model JSON is inconsistent: feature_names, mean, scale must be the same length"
        )

    feature_comment = ", ".join(feature_names)
    mean_str = _format_float_array(mean)
    scale_str = _format_float_array(scale)

    return (
        "/*\n"
        " * Auto-generated by scripts/export_model_to_c.py.\n"
        " * Do not edit by hand. Regenerate after retraining the model.\n"
        f" * Feature order: {feature_comment}\n"
        " */\n"
        "\n"
        "#ifndef TPM_MODEL_PARAMS_H\n"
        "#define TPM_MODEL_PARAMS_H\n"
        "\n"
        '#include "inference.h"\n'
        "\n"
        f"#define TPM_MODEL_N_FEATURES {n}u\n"
        "\n"
        "static const float tpm_model_mean[TPM_MODEL_N_FEATURES] = {\n"
        f"{mean_str}\n"
        "};\n"
        "\n"
        "static const float tpm_model_scale[TPM_MODEL_N_FEATURES] = {\n"
        f"{scale_str}\n"
        "};\n"
        "\n"
        f"static const tpm_centroid_model_t {struct_name} = {{\n"
        "    .n_features = TPM_MODEL_N_FEATURES,\n"
        "    .mean = tpm_model_mean,\n"
        "    .scale = tpm_model_scale,\n"
        f"    .threshold = {threshold:.9e}f,\n"
        "};\n"
        "\n"
        "#endif /* TPM_MODEL_PARAMS_H */\n"
    )


def render_fixed_header(payload: dict, struct_name: str) -> str:
    """Build a Q24.8 fixed-point C model header from JSON payload.

    The generated arrays are consumed by ``firmware/inference_fixed.c``. The
    header stores reciprocal scale so inference uses multiply + shift instead
    of runtime division, which is the usual embedded fixed-point tradeoff.
    """

    model = CentroidAnomalyDetector(
        feature_names=list(payload["feature_names"]),
        mean=np.asarray(payload["mean"], dtype=np.float32),
        scale=np.asarray(payload["scale"], dtype=np.float32),
        threshold=float(payload["threshold"]),
    )
    fixed = FixedPointCentroid.from_float_model(model)
    n = len(model.feature_names)
    feature_comment = ", ".join(model.feature_names)
    mean_q = _format_int32_array(fixed.mean_q.tolist())
    inv_scale_q = _format_int32_array(fixed.inv_scale_q.tolist())

    return (
        "/*\n"
        " * Auto-generated by scripts/export_model_to_c.py.\n"
        " * Do not edit by hand. Regenerate after retraining the model.\n"
        f" * Q format: signed Q24.{Q_FRACTIONAL_BITS}\n"
        f" * Feature order: {feature_comment}\n"
        " */\n"
        "\n"
        "#ifndef TPM_MODEL_PARAMS_FIXED_H\n"
        "#define TPM_MODEL_PARAMS_FIXED_H\n"
        "\n"
        '#include "inference_fixed.h"\n'
        "\n"
        f"#define TPM_FIXED_MODEL_N_FEATURES {n}u\n"
        f"#define TPM_FIXED_MODEL_Q_FRACTIONAL_BITS {Q_FRACTIONAL_BITS}u\n"
        "\n"
        "static const int32_t tpm_model_mean_q[TPM_FIXED_MODEL_N_FEATURES] = {\n"
        f"{mean_q}\n"
        "};\n"
        "\n"
        "static const int32_t tpm_model_inv_scale_q[TPM_FIXED_MODEL_N_FEATURES] = {\n"
        f"{inv_scale_q}\n"
        "};\n"
        "\n"
        f"static const tpm_centroid_fixed_model_t {struct_name} = {{\n"
        "    .n_features = TPM_FIXED_MODEL_N_FEATURES,\n"
        "    .mean_q = tpm_model_mean_q,\n"
        "    .inv_scale_q = tpm_model_inv_scale_q,\n"
        f"    .threshold_q = {fixed.threshold_q},\n"
        "};\n"
        "\n"
        "#endif /* TPM_MODEL_PARAMS_FIXED_H */\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export JSON centroid model as C header.")
    parser.add_argument("--model", default="artifacts/model.json")
    parser.add_argument("--out", default="firmware/model_params.h")
    parser.add_argument(
        "--fixed-out",
        default=None,
        help="Optional output path for Q24.8 fixed-point model parameters.",
    )
    parser.add_argument(
        "--name",
        default="g_centroid_model",
        help="Identifier for the generated tpm_centroid_model_t struct.",
    )
    parser.add_argument(
        "--fixed-name",
        default="g_centroid_fixed_model",
        help="Identifier for the generated tpm_centroid_fixed_model_t struct.",
    )
    args = parser.parse_args()

    payload = json.loads(Path(args.model).read_text(encoding="utf-8"))
    if payload.get("type") != "centroid_anomaly_detector":
        # Soft warning. The header would still be written, but the user should
        # know they exported the wrong file before flashing it.
        print(
            f"warning: {args.model} type is {payload.get('type')!r}, expected "
            "'centroid_anomaly_detector'. The generated header may be incorrect."
        )

    header = render_header(payload, args.name)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8")

    bytes_per_float = 4
    flash_estimate = 2 * len(payload["feature_names"]) * bytes_per_float + 4
    print(f"wrote {out_path} ({out_path.stat().st_size} source bytes)")
    print(f"estimated MCU flash for parameters: {flash_estimate} bytes")

    if args.fixed_out is not None:
        fixed_header = render_fixed_header(payload, args.fixed_name)
        fixed_out_path = Path(args.fixed_out)
        fixed_out_path.parent.mkdir(parents=True, exist_ok=True)
        fixed_out_path.write_text(fixed_header, encoding="utf-8")
        fixed_flash_estimate = 2 * len(payload["feature_names"]) * 4 + 4
        print(f"wrote {fixed_out_path} ({fixed_out_path.stat().st_size} source bytes)")
        print(f"estimated MCU flash for fixed-point parameters: {fixed_flash_estimate} bytes")


if __name__ == "__main__":
    main()
