/*
 * Auto-generated by scripts/export_model_to_c.py.
 * Do not edit by hand. Regenerate after retraining the model.
 * Q format: signed Q24.8
 * Feature order: rms, std, peak_to_peak, crest_factor, kurtosis, dominant_freq_hz, spectral_centroid_hz, low_band_power, mid_band_power, high_band_power
 */

#ifndef TPM_MODEL_PARAMS_FIXED_H
#define TPM_MODEL_PARAMS_FIXED_H

#include "inference_fixed.h"

#define TPM_FIXED_MODEL_N_FEATURES 10u
#define TPM_FIXED_MODEL_Q_FRACTIONAL_BITS 8u

static const int32_t tpm_model_mean_q[TPM_FIXED_MODEL_N_FEATURES] = {
    110, 110, 353, 420, 405, 16000,
    17155, 241, 13, 2
};

static const int32_t tpm_model_inv_scale_q[TPM_FIXED_MODEL_N_FEATURES] = {
    90622, 90622, 8878, 5910, 14053, 256000000,
    93, 17840, 21424, 86023
};

static const tpm_centroid_fixed_model_t g_centroid_fixed_model = {
    .n_features = TPM_FIXED_MODEL_N_FEATURES,
    .mean_q = tpm_model_mean_q,
    .inv_scale_q = tpm_model_inv_scale_q,
    .threshold_q = 1559,
};

#endif /* TPM_MODEL_PARAMS_FIXED_H */
