/*
 * Auto-generated by scripts/export_model_to_c.py.
 * Do not edit by hand. Regenerate after retraining the model.
 * Feature order: rms, std, peak_to_peak, crest_factor, kurtosis, dominant_freq_hz, spectral_centroid_hz, low_band_power, mid_band_power, high_band_power
 */

#ifndef TPM_MODEL_PARAMS_H
#define TPM_MODEL_PARAMS_H

#include "inference.h"

#define TPM_MODEL_N_FEATURES 10u

static const float tpm_model_mean[TPM_MODEL_N_FEATURES] = {
    4.294175208e-01f, 4.294175208e-01f, 1.379570365e+00f, 1.642246962e+00f,
    1.580165386e+00f, 6.250000000e+01f, 6.701230621e+01f, 9.407957196e-01f,
    5.018853769e-02f, 8.926285431e-03f
};

static const float tpm_model_scale[TPM_MODEL_N_FEATURES] = {
    2.824935364e-03f, 2.824935364e-03f, 2.883483469e-02f, 4.331334680e-02f,
    1.821611263e-02f, 9.999999975e-07f, 2.755547047e+00f, 1.435008645e-02f,
    1.194941625e-02f, 2.975961659e-03f
};

static const tpm_centroid_model_t g_centroid_model = {
    .n_features = TPM_MODEL_N_FEATURES,
    .mean = tpm_model_mean,
    .scale = tpm_model_scale,
    .threshold = 6.088618279e+00f,
};

#endif /* TPM_MODEL_PARAMS_H */
